apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: onyl1v70z-nodejs
  janus-idp.io/tekton: onyl1v70z-nodejs
  backstage.io/kubernetes-id: onyl1v70z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: onyl1v70z-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
