apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: onyl1v70z-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: onyl1v70z-nodejs 
  name: onyl1v70z-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: onyl1v70z-nodejs 
